app:
  BluePayService:               # 应用 A
    users:
      admin:
        encrypt:
          type: aes
          key: "0123456789abcdef0123456789abcdef"
      reviewer:
        encrypt:
          type: aes
          key: "0123456789abcdef0123456789abcdef"

  BluePayApp:              # 应用 B
    users:
      c-user:
        encrypt:
          type: aes
          key: "abcdef0123456789abcdef0123456789"
          iv:  "1234567890abcdef"
